<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSendMoney</name>
   <tag></tag>
   <elementGuidId>8d1c2b93-51c2-490e-aed2-eb4d5d716640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class = 'btn-primary btn btn-md']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.bd-form-footer__button.bd-form-footer__button--positive.bd-button__primary.bd-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45decf20-d04a-4f18-b28d-277cc5ed8c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bd-form-footer__button bd-form-footer__button--positive bd-button__primary bd-button</value>
      <webElementGuid>6c941ae8-c48b-44a8-b518-974ff216a12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eb-analytics</name>
      <type>Main</type>
      <value>{label:'?parent|?text'}</value>
      <webElementGuid>2ff85452-bb1e-47b9-b5f5-9ee1b0e31d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>activeStep.id === 'verify' &amp;&amp; $params.visibility.accept</value>
      <webElementGuid>8edc608d-b2a9-478f-a643-c9a41ef4e6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eb-single-click</name>
      <type>Main</type>
      <value>moveNext()</value>
      <webElementGuid>776d720e-9326-482a-b112-bf7c3caeabfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a6dbbe6-f306-4014-b5c8-62e4216b7107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chấp nhận</value>
      <webElementGuid>9b4cfbef-1e21-417d-ac1f-8f1d0b87372d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;animate-on am-fade-and-scale drawer-content&quot;]/eb-ocb-full-screen-widget[1]/div[@class=&quot;payments_miniapp&quot;]/div[1]/div[1]/div[@class=&quot;eb-screen-content&quot;]/div[1]/div[@class=&quot;animate-on am-fade-and-scale&quot;]/div[@class=&quot;rb-content-view--framed rb-payments-new form fast-payment rb-content-view&quot;]/div[@class=&quot;rb-content-view__placeholder&quot;]/div[@class=&quot;rb-content-view__content&quot;]/div[@class=&quot;rb-content-view__inner&quot;]/section[2]/div[@class=&quot;bd-form-panel--responsive bd-form-panel&quot;]/div[@class=&quot;rb-multistep-form rb-multistep-form-step-verify&quot;]/div[3]/div[@class=&quot;bd-form-footer--stackable form-btm form-footer&quot;]/div[@class=&quot;right mobile-no-float&quot;]/button[@class=&quot;bd-form-footer__button bd-form-footer__button--positive bd-button__primary bd-button&quot;]</value>
      <webElementGuid>db2fc233-1752-471b-ac44-c6054050edc3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
