<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputTransferAmount</name>
   <tag></tag>
   <elementGuidId>26d07969-0fec-4cf8-99fa-797e24805cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;amount&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='amount-input']//*[starts-with(@id , 'mat-input')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb7ed7e1-2e83-4ab9-a1d8-53b21a3032f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3343a8d-185e-4563-8b43-6b63b6e54023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>e5ac145a-92e2-4c56-8f5b-9a75d110e1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-min</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>ba77b252-b2b6-4d09-8c44-f2d7a0a289b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field ng-pristine ng-untouched ng-valid-ng-min ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-funds ng-valid-validate-minimum-balance ng-valid-more-than-available</value>
      <webElementGuid>c21941de-7006-45ea-9711-d52e1adc66ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payment.formData.amount</value>
      <webElementGuid>0660ac84-a37b-4f4f-9cdb-338eae699ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^(0(\.\d{1,2})?|[1-9](\d)*|[1-9]\d{0,2}(,\d{3})*(\.\d{1,2})?)$/</value>
      <webElementGuid>d07698c6-ccc1-430a-922f-564d294252b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>checkDisableTransferButton()</value>
      <webElementGuid>c355d3f1-3111-4e72-a905-a94b7c25c6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập số tiền cần chuyển</value>
      <webElementGuid>4b031d44-a8e2-4b1d-a52e-b0bf35419942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currency</name>
      <type>Main</type>
      <value>VND</value>
      <webElementGuid>f8d94472-9c43-4ff9-80d4-7b65adc78aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7444775d-0c31-41ea-87e8-c64c66addf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;animate-on am-fade-and-scale drawer-content&quot;]/eb-ocb-full-screen-widget[1]/div[@class=&quot;payments_miniapp&quot;]/div[1]/div[1]/div[@class=&quot;eb-screen-content&quot;]/div[1]/div[@class=&quot;animate-on am-fade-and-scale&quot;]/div[@class=&quot;rb-content-view--framed rb-payments-new form fast-payment rb-content-view&quot;]/div[@class=&quot;rb-content-view__placeholder&quot;]/div[@class=&quot;rb-content-view__content&quot;]/div[@class=&quot;rb-content-view__inner&quot;]/section[2]/div[@class=&quot;bd-form-panel--responsive bd-form-panel&quot;]/div[@class=&quot;rb-multistep-form rb-multistep-form-step-fill&quot;]/div[@class=&quot;row bd-form-content&quot;]/ng-transclude[1]/div[1]/div[1]/form[@class=&quot;ng-pristine ng-valid-ng-min ng-invalid ng-invalid-required ng-valid-pattern ng-valid-split-text-max-length ng-valid-maxlength ng-valid-funds ng-valid-validate-minimum-balance ng-valid-more-than-available&quot;]/div[@class=&quot;bd-form&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;control-has-indicator&quot;]/input[@class=&quot;input-field ng-pristine ng-untouched ng-valid-ng-min ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-funds ng-valid-validate-minimum-balance ng-valid-more-than-available&quot;]</value>
      <webElementGuid>0a0c474d-bacb-4a35-9413-eaaa5d5a4c9c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
