<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputDescription</name>
   <tag></tag>
   <elementGuidId>b1af7c24-bb7c-4bfe-8fd3-207bae3f5cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='control']//*[@name = 'description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a84b7932-0a7b-4b73-8100-95bf1df910f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>payment.meta.maxDescriptionLength</value>
      <webElementGuid>b09fa3f0-5f57-4c8c-b272-17a93d023a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>7fb14a44-7b57-4770-9bc8-e0f7f7e9729e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payment.formData.description</value>
      <webElementGuid>adc70a44-4303-4d21-9122-73589d1befab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field input-area--payment-description ng-pristine ng-untouched ng-empty ng-valid-split-text-max-length ng-invalid ng-invalid-required ng-valid-pattern</value>
      <webElementGuid>21449dc8-3c83-4bf4-8f29-20c9b160a035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>split-text-max-length-validators</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>9c3e537f-6593-4903-81cc-394958dcac20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[a-zA-ZĄąŚśĘęŻżŹźĆćŃńŁłÓó\d \.,]*$/</value>
      <webElementGuid>09903f62-a440-4c47-b9c0-6f29e35294e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>checkDisableTransferButton()</value>
      <webElementGuid>8a4b14fa-70e1-4d7f-aec9-ec2292d2c6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập nội dung</value>
      <webElementGuid>138c6a6d-d914-4150-8f61-c76fd191e789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9840fd8a-88c5-49a5-8f0a-90b6589a803c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;animate-on am-fade-and-scale drawer-content&quot;]/eb-ocb-full-screen-widget[1]/div[@class=&quot;payments_miniapp&quot;]/div[1]/div[1]/div[@class=&quot;eb-screen-content&quot;]/div[1]/div[@class=&quot;animate-on am-fade-and-scale&quot;]/div[@class=&quot;rb-content-view--framed rb-payments-new form fast-payment rb-content-view&quot;]/div[@class=&quot;rb-content-view__placeholder&quot;]/div[@class=&quot;rb-content-view__content&quot;]/div[@class=&quot;rb-content-view__inner&quot;]/section[2]/div[@class=&quot;bd-form-panel--responsive bd-form-panel&quot;]/div[@class=&quot;rb-multistep-form rb-multistep-form-step-fill&quot;]/div[@class=&quot;row bd-form-content&quot;]/ng-transclude[1]/div[1]/div[1]/form[@class=&quot;ng-pristine ng-valid-ng-min ng-invalid ng-invalid-required ng-valid-pattern ng-valid-split-text-max-length ng-valid-maxlength ng-valid-funds ng-valid-validate-minimum-balance ng-valid-more-than-available&quot;]/div[@class=&quot;bd-form&quot;]/div[@class=&quot;bd-item-property--multirow form-row&quot;]/div[@class=&quot;control&quot;]/textarea[@class=&quot;input-field input-area--payment-description ng-pristine ng-untouched ng-empty ng-valid-split-text-max-length ng-invalid ng-invalid-required ng-valid-pattern&quot;]</value>
      <webElementGuid>94ed91c2-93e6-41eb-b08a-9c52087539e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
