<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tabTranfermoney</name>
   <tag></tag>
   <elementGuidId>be60d815-4024-4a33-97ab-608e6b2f3ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[contains(text(), &quot;${text}&quot;)])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a5d1768-134d-4b4d-8b75-89cbc6e6a9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eb-analytics</name>
      <type>Main</type>
      <value>{event: 'click', action:'Click', category:'=Menu', label:item.title}</value>
      <webElementGuid>e67637a9-f500-477b-864c-9e5abdc24a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chuyển nhận tiền</value>
      <webElementGuid>cbd463b2-dc17-42a5-8547-f9e16830f908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-nav&quot;)/ul[@class=&quot;nav-ul&quot;]/li[@class=&quot;active&quot;]/div[@class=&quot;ahref&quot;]/span[2]</value>
      <webElementGuid>0b89cec7-b65d-4051-8580-ff96cb56e10b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
