<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnGetOTPTransferMoney</name>
   <tag></tag>
   <elementGuidId>48803a1b-57c1-4c29-b2e4-aa4776136549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.otp-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class='otp-btn'][(text() = 'Lấy OTP' or . = 'Lấy OTP')])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c90095bf-1cf4-45c7-bac8-6a67907f1192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>rbModel.$tokenType==='SMS' || rbModel.$tokenType==='NEW_OTP'</value>
      <webElementGuid>e3de78a9-b6fe-495a-9109-beb584515a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-btn</value>
      <webElementGuid>1bba53e3-da5b-440a-b228-7c344702456f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>getOTP()</value>
      <webElementGuid>21a867e2-9ce1-466f-ad1d-c98df7f42c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lấy OTP</value>
      <webElementGuid>90e34f50-e9a4-43e5-8b6c-8c930467bcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;animate-on am-fade-and-scale drawer-content&quot;]/eb-ocb-full-screen-widget[1]/div[@class=&quot;payments_miniapp&quot;]/div[1]/div[1]/div[@class=&quot;eb-screen-content&quot;]/div[1]/div[@class=&quot;animate-on am-fade-and-scale&quot;]/div[@class=&quot;rb-content-view--framed rb-payments-new form fast-payment rb-content-view&quot;]/div[@class=&quot;rb-content-view__placeholder&quot;]/div[@class=&quot;rb-content-view__content&quot;]/div[@class=&quot;rb-content-view__inner&quot;]/section[2]/div[@class=&quot;bd-form-panel--responsive bd-form-panel&quot;]/div[@class=&quot;rb-multistep-form rb-multistep-form-step-verify&quot;]/div[@class=&quot;row bd-form-content&quot;]/ng-transclude[1]/div[1]/div[1]/div[@class=&quot;form-pane&quot;]/div[@class=&quot;pane-above&quot;]/rb-token-authorization[1]/section[@class=&quot;rb-token-authorization&quot;]/form[@class=&quot;tokenForm ng-pristine ng-valid-pattern ng-invalid ng-invalid-required&quot;]/section[@class=&quot;otp-subsection&quot;]/button[@class=&quot;otp-btn&quot;]</value>
      <webElementGuid>0deb596a-a622-4c1d-bc4f-7d405e0cef7b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
