<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonAccept</name>
   <tag></tag>
   <elementGuidId>1bd3d735-a2cd-4feb-89ba-720734cd4e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.bd-button.bd-button__primary_new.bd-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='bd-form-footer__button bd-form-footer__button--positive bd-button__primary bd-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91d35b40-3e7a-4710-9589-cff0392493c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bd-button bd-button__primary_new bd-button</value>
      <webElementGuid>05c6978c-e7d2-4348-93a9-15a25861ad1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>eb-analytics</name>
      <type>Main</type>
      <value>{label:'?parent|?text'}</value>
      <webElementGuid>03147227-a924-4095-9597-d4ece61063dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>5436b327-11b3-4e5f-b422-635e23da4625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accounts&quot;)/div[@class=&quot;widget-tile-content&quot;]/div[@class=&quot;widget-content-inner&quot;]/div[@class=&quot;horizontal-split-panels&quot;]/section[@class=&quot;hover_background&quot;]/div[@class=&quot;row widget-content-paddings&quot;]/div[@class=&quot;col-xs-10&quot;]/div[@class=&quot;widget-configuration&quot;]/div[@class=&quot;option first&quot;]/div[@class=&quot;option__actions&quot;]/div[@class=&quot;save&quot;]/button[@class=&quot;bd-button bd-button__primary_new bd-button&quot;]</value>
      <webElementGuid>4fb18f85-6370-47f7-8cc2-f6d9cbb0110e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
