<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputOTP</name>
   <tag></tag>
   <elementGuidId>a179a140-6660-4e1b-b310-73b2a31917e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authorizationCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='authorizationCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9512d9b-0dc8-4e67-ab53-a040db7446ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'ng-invalid' : (showWrongCodeLabel === true || showWrongCodeLabelShort === true)}</value>
      <webElementGuid>b4efec10-ad51-4d19-b85b-964cd4218947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rb-authorization__input input-field padding-helper-1 input-otp input-pki input-hw ng-pristine ng-untouched ng-empty ng-valid-pattern ng-invalid ng-invalid-required</value>
      <webElementGuid>ceb523c8-dc20-4d82-b300-f15cf6d1d913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>[0-9]+</value>
      <webElementGuid>b938aeba-709d-4584-bb60-e47a72b830d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tokenInput</value>
      <webElementGuid>99b02d5e-27d2-4098-a46f-f019dc00aaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>rbModel.input.model</value>
      <webElementGuid>0acc605d-bbc0-4ac6-ae1a-22d7baf1752a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorizationCode</value>
      <webElementGuid>25872ced-5e68-4f4a-bd4b-02a41ca35660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>rbModel.$tokenRequired</value>
      <webElementGuid>26427590-ffc3-451e-8d63-0416daf61d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>token.tokenPromise.$$state.status !== 0 &amp;&amp; rbModel.view.name===VIEW_NAMES.FORM &amp;&amp; token.response</value>
      <webElementGuid>38bdfc37-6d04-43d3-a5f1-2d21925540af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập OTP</value>
      <webElementGuid>90ba35dd-6547-4c04-bc6b-636d00e9b86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb37cc4c-24a9-4c50-aa78-87db8911a763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee18bd10-1aae-4c48-ae6f-149dd96fc50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>rbModel.$tokenType==='PKI'</value>
      <webElementGuid>4dbb5b4d-749b-4bd9-9354-6b0d6a8d2a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f30ea073-dc10-4b9b-b7b3-caa09380a5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8aba20ed-1909-47ca-a4a2-1d1ce0de47da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f3c90ecb-4644-421c-b0db-8025ae83f03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorizationCode&quot;)</value>
      <webElementGuid>c768b0b2-2a04-4c34-b42f-ae72ed60534a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
