<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAdsPopupCancel</name>
   <tag></tag>
   <elementGuidId>9fa6e320-2526-4730-a4eb-9d41f0c2baba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='x-button-popup-login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.x-button-popup-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12b0eedd-c9f7-4db9-bc97-950d47cc65dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-button-popup-login</value>
      <webElementGuid>ecf6806a-80bf-4f13-94b2-88e41f71e246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>hidePopupLogin()</value>
      <webElementGuid>ac6c70f0-d468-498b-819d-df61ea81b3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>999986cb-0325-499d-ba38-70dfc2ece17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>022fb95f-b602-43e8-9e3a-11ff828e6031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                X
                            </value>
      <webElementGuid>0e270da7-c696-470c-9e71-83aab2a95430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;popup-login-area&quot;]/div[@class=&quot;popup-login&quot;]/div[@class=&quot;x-button-popup-login&quot;]</value>
      <webElementGuid>432b8085-43c1-408f-a3f0-acb3d931c3a5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
