<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnNext</name>
   <tag></tag>
   <elementGuidId>d8cb97cc-9a40-4ea9-a0ce-1660bc897eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='loginSubmitButton']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginSubmitButton > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4533b864-8910-4929-ac07-b4aa67e3a870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếp tục</value>
      <webElementGuid>e8b51f1f-552e-4b8e-af4f-4fbc812b0c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginSubmitButton&quot;)/span[1]</value>
      <webElementGuid>817aad15-9cb0-4e6d-86ac-b2ea91415eb6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
